name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_web:
    runs-on: ubuntu-latest
    name: Build web

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :composeApp:jsBrowserDistribution

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ github.workspace }}/composeApp/build/dist/js/productionExecutable

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

